#!/bin/bash

# Critical Technologies Inc. (CTI)
# Adam Wiethuechter <adam.wiethuechter@critical.com>
# April 25, 2019

print_message() 
{
	echo
	echo "Welcome to CTI HIP to DNS Creator!"
	echo
}

display_usage()
{
	echo
	echo "Usage:"
	echo "	sudo $0 -a <path_to_my_host_id_file> <fqdn_of_rvs_server>"
	echo "	sudo $0 -d <path_to_my_host_id_file>"
	echo "	$0 -r <fqdn_of_rvs_server>"
	echo
	echo "Options:"
	echo "	-h, --help           Display usage instructions"
	echo "	-a, --all            Create HIP RR + RVS Entry for DJBDNS"
	echo "	-d, --hip-to-dns     Create HIP RR Entry for DJBDNS"
	echo "	-r, --rvs-djbdns     Create RVS Entry for DJBDNS"
	echo "	-h, --help           Display usage instructions"
	echo
}

hip_to_dns()
{
	sudo /usr/local/sbin/hi2dns --djb $1 > my_hi2dns
}

djbdns_rvs()
{
	/usr/local/sbin/djbrvs $1 > my_rvs
}

raise_error() 
{
	local error_message="$@"
	echo "${error_message}" 1>&2;
}

case $1 in
	-a|--all)
		echo "Creating an HIP RR record and RVS entry for DJBDNS..."
		hip_to_dns $2
		djbdns_rvs $3
		echo `cat my_hi2dns``tail -1 my_rvs` > my_hi2dns_rvs
		;;
	-d|--hip-to-dns)
		echo "Creating an HIP RR record for DJBDNS..."
		hip_to_dns $2
		;;
	-r|--rvs-djbdns)
		echo "Creating an RVS entry for DJBDNS..."
		djbdns_rvs $2
		;;
	-h|--help)
		display_usage
		;;
	-p|--print)
		print_message
		;;
	*)
		raise_error "Unknown argument: $1"
		display_usage
		;;
esac

exit 0